"""
Semabridge Initialization Module.

Provides repository bootstrapping and global configuration generation.
Follows atomic initialization pattern with migration support for existing databases.
"""

from __future__ import annotations

import os
from datetime import datetime
from pathlib import Path
from typing import Optional, Dict, Any

import duckdb
import yaml
from copy import deepcopy
from pydantic import BaseModel

from semabridge.utils.logger import get_logger

logger = get_logger(__name__)


class InitResult(BaseModel):
    """Result of initialization operation."""
    success: bool
    repository_path: Path
    config_path: Optional[Path] = None
    message: str
    migrated: bool = False  # True if existing DB was migrated


# Default global configuration template for config.yaml
DEFAULT_CONFIG = {
    "core": {
        "intermediate_format": "OSI",
        "repository_path": "~/.semabridge/semabridge.db",
        "backup_retention": 5,
    },
    "llm": {
        "enabled": False,
        "model": "gpt-4o-mini",
        "timeout_seconds": 30,
        "max_retries": 3,
        "api_key_env": "OPENAI_API_KEY",
    },
    "logging": {
        "level": "INFO",
        "format": "text",
        "dir": "~/.semabridge/logs",
        "redact_secrets": True,
    },
    "concurrency": {
        "max_concurrent_models": 4,
        "thread_pool_size": 8,
    },
    "options": {
        "global_exclude_models": [],
    },
    "config_path": "",  # auto-populated during init
}

GLOBAL_CONFIG_FILENAME = "config.yaml"
"""The global config is a separate entity from semabridge.yaml."""

CONFIG_YAML_HEADER = """# Semabridge Global Configuration (config.yaml)
# ============================================
# This file is SEPARATE from the project-level semabridge.yaml.
# It stores system-wide settings for logging, LLM, concurrency, etc.
#
# Generated by : semabridge init
# Generated at : {timestamp}
# Documentation: https://docs.semabridge.io/config
#
# IMPORTANT: Do NOT store secrets here. Use environment variables.

"""


class SemabridgeInitializer:
    """
    Initializes Semabridge repository and global configuration.
    
    Supports:
    - Local mode (--local): Creates repository in current working directory
    - Global mode: Creates repository in ~/.semabridge/
    - Migration: Updates existing databases to new schema without deletion
    """
    
    def __init__(
        self,
        repository_path: Optional[Path] = None,
        config_path: Optional[Path] = None,
        local: bool = False,
        log_dir: Optional[str] = None,
    ):
        """
        Initialize with target repository path.
        
        Args:
            repository_path: Custom path for repository. If None, uses default.
            local: If True, use current working directory for repository.
        """
        self.local = local
        
        if local:
            self.repository_path = Path.cwd() / "semabridge.db"
            self.config_dir = Path.cwd()
            self.default_log_dir = u"./logs"
        elif repository_path:
            raw_path = Path(repository_path).expanduser().resolve()
            if raw_path.is_dir():
                # If a directory is provided, append default filename
                self.repository_path = raw_path / "semabridge.db"
                logger.info(f"Directory provided for repository; using: {self.repository_path}")
            else:
                self.repository_path = raw_path
            self.config_dir = self.repository_path.parent
            self.default_log_dir = u"~/.semabridge/logs"
        else:
            # Default: ~/.semabridge/
            self.config_dir = Path.home() / ".semabridge"
            self.repository_path = self.config_dir / "semabridge.db"
            self.default_log_dir = u"~/.semabridge/logs"
        
        self.config_path = config_path or (self.config_dir / GLOBAL_CONFIG_FILENAME)
        self.log_dir = log_dir
    
    def initialize(self) -> InitResult:
        """
        Perform atomic initialization.
        
        1. Create directory structure if needed
        2. Create or migrate DuckDB repository
        3. Generate global config.yaml
        
        Returns:
            InitResult with paths and status
        """
        try:
            # Step 1: Create directory
            self._ensure_directory()
            
            # Step 2: Create or migrate repository
            migrated = self._create_or_migrate_repository()
            
            # Step 3: Generate config (only if not exists)
            config_created = self._generate_config()
            
            message = "Semabridge initialized successfully."
            if migrated:
                message = "Semabridge repository migrated to latest schema."
            elif not config_created:
                message = "Semabridge already initialized. Config unchanged."
            
            return InitResult(
                success=True,
                repository_path=self.repository_path,
                config_path=self.config_path if config_created else None,
                message=message,
                migrated=migrated,
            )
            
        except PermissionError as e:
            logger.error(f"Permission denied: {e}")
            return InitResult(
                success=False,
                repository_path=self.repository_path,
                message=f"Permission denied: Cannot write to {self.config_dir}. "
                        f"Check directory permissions or use --path to specify a different location.",
            )
        except Exception as e:
            logger.error(f"Initialization failed: {e}")
            return InitResult(
                success=False,
                repository_path=self.repository_path,
                message=f"Initialization failed: {str(e)}",
            )
    
    def _ensure_directory(self) -> None:
        """Create repository directory if it doesn't exist."""
        self.config_dir.mkdir(parents=True, exist_ok=True)
        logger.debug(f"Ensured directory exists: {self.config_dir}")
    
    def _create_or_migrate_repository(self) -> bool:
        """
        Create DuckDB repository or migrate existing one.
        
        Returns:
            True if migration was performed, False for new creation
        """
        db_exists = self.repository_path.exists()
        
        # Connect and initialize/migrate schema
        conn = duckdb.connect(str(self.repository_path))
        try:
            migrated = self._init_schema(conn, is_existing=db_exists)
            conn.execute("CHECKPOINT")  # Consolidate WAL
            return migrated
        finally:
            conn.close()
    
    def _init_schema(self, conn: duckdb.DuckDBPyConnection, is_existing: bool) -> bool:
        """
        Initialize or migrate database schema.
        
        Preserves existing data while adding new tables/columns.
        
        Returns:
            True if migration was performed
        """
        migrated = False
        
        # Core tables (CREATE IF NOT EXISTS = safe for migration)
        conn.execute("""
            CREATE TABLE IF NOT EXISTS projects (
                project_id VARCHAR PRIMARY KEY,
                name VARCHAR NOT NULL,
                workspace_id VARCHAR,
                adapter VARCHAR,
                source_connection VARCHAR,
                last_updated TIMESTAMP
            );
            
            CREATE TABLE IF NOT EXISTS snapshots (
                snapshot_id VARCHAR PRIMARY KEY,
                project_id VARCHAR NOT NULL,
                timestamp TIMESTAMP NOT NULL,
                version_tag VARCHAR,
                sml_blob JSON,
                status VARCHAR DEFAULT 'success',
                duration_ms INTEGER,
                error_message VARCHAR,
                initiated_by VARCHAR DEFAULT 'cli',
                run_id VARCHAR,
                FOREIGN KEY (project_id) REFERENCES projects(project_id)
            );
            
            CREATE TABLE IF NOT EXISTS changes (
                change_id VARCHAR PRIMARY KEY,
                snapshot_id VARCHAR NOT NULL,
                object_type VARCHAR,
                object_name VARCHAR,
                diff_type VARCHAR,
                old_value JSON,
                new_value JSON,
                FOREIGN KEY (snapshot_id) REFERENCES snapshots(snapshot_id)
            );
            
            CREATE TABLE IF NOT EXISTS runs (
                run_id VARCHAR PRIMARY KEY,
                project_id VARCHAR NOT NULL,
                started_at TIMESTAMP NOT NULL,
                completed_at TIMESTAMP,
                status VARCHAR NOT NULL DEFAULT 'running',
                final_step INTEGER,
                source_type VARCHAR,
                target_type VARCHAR,
                error_message VARCHAR,
                duration_ms INTEGER
            );
            
            CREATE TABLE IF NOT EXISTS source_artifacts (
                artifact_id VARCHAR PRIMARY KEY,
                run_id VARCHAR NOT NULL,
                source_type VARCHAR NOT NULL,
                content_json JSON NOT NULL,
                created_at TIMESTAMP NOT NULL
            );
            
            -- New: Global configuration metadata (v1.2)
            CREATE TABLE IF NOT EXISTS semabridge_meta (
                key VARCHAR PRIMARY KEY,
                value VARCHAR,
                updated_at TIMESTAMP
            );
        """)
        
        # Perform schema migrations for existing databases
        if is_existing:
            migrated = self._migrate_schema(conn)
        
        # Record schema version
        conn.execute("""
            INSERT INTO semabridge_meta (key, value, updated_at)
            VALUES ('schema_version', '1.2', CURRENT_TIMESTAMP)
            ON CONFLICT (key) DO UPDATE SET 
                value = excluded.value,
                updated_at = excluded.updated_at
        """)
        
        return migrated
    
    def _migrate_schema(self, conn: duckdb.DuckDBPyConnection) -> bool:
        """
        Migrate existing schema to latest version.
        
        Non-destructive: Only adds new columns/tables, never drops.
        
        Returns:
            True if any migrations were applied
        """
        migrations_applied = False
        
        # Get existing tables
        tables = {r[0] for r in conn.execute(
            "SELECT table_name FROM information_schema.tables WHERE table_schema = 'main'"
        ).fetchall()}
        
        # Migration: projects table columns
        if 'projects' in tables:
            cols = {c[1] for c in conn.execute("PRAGMA table_info('projects')").fetchall()}
            if 'adapter' not in cols:
                conn.execute("ALTER TABLE projects ADD COLUMN adapter VARCHAR")
                migrations_applied = True
            if 'source_connection' not in cols:
                conn.execute("ALTER TABLE projects ADD COLUMN source_connection VARCHAR")
                migrations_applied = True
        
        # Migration: snapshots table columns
        if 'snapshots' in tables:
            cols = {c[1] for c in conn.execute("PRAGMA table_info('snapshots')").fetchall()}
            new_cols = {
                'status': "VARCHAR DEFAULT 'success'",
                'duration_ms': "INTEGER",
                'error_message': "VARCHAR",
                'initiated_by': "VARCHAR DEFAULT 'cli'",
                'run_id': "VARCHAR",
            }
            for col, col_type in new_cols.items():
                if col not in cols:
                    conn.execute(f"ALTER TABLE snapshots ADD COLUMN {col} {col_type}")
                    migrations_applied = True
        
        if migrations_applied:
            logger.info("Schema migrations applied successfully")
        
        return migrations_applied
    
    def _generate_config(self) -> bool:
        """
        Generate global config.yaml with defaults.
        
        Returns:
            True if config was created, False if already exists
        """
        if self.config_path.exists():
            logger.debug(f"Config already exists: {self.config_path}")
            return False
        
        # Generate YAML content with header
        config = deepcopy(DEFAULT_CONFIG)
        config["core"]["repository_path"] = str(self.repository_path)

        # Self-referential: store the path of this config file in itself
        config["config_path"] = str(self.config_path)
        
        if self.log_dir:
             config["logging"]["dir"] = self.log_dir
        elif self.local:
             config["logging"]["dir"] = "./logs"
        
        yaml_content = CONFIG_YAML_HEADER.format(
            timestamp=datetime.now().isoformat()
        )
        yaml_content += yaml.dump(config, default_flow_style=False, sort_keys=False)
        
        self.config_path.write_text(yaml_content, encoding="utf-8")
        logger.info(f"Generated global config: {self.config_path}")
        logger.info(
            f"Note: config.yaml is stored alongside the DuckDB repository at "
            f"{self.config_dir}"
        )
        
        return True
    
    @staticmethod
    def get_default_repository_path() -> Path:
        """Get the default repository path."""
        return Path.home() / ".semabridge" / "semabridge.db"
    
    @staticmethod
    def get_default_config_path() -> Path:
        """Get the default global config path (config.yaml)."""
        return Path.home() / ".semabridge" / GLOBAL_CONFIG_FILENAME
